// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(System.AppContext))]
    [Migration("20210329172742_MigrationName")]
    partial class MigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.Lecturer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("lecturer_pkey");

                    b.ToTable("lecturers");
                });

            modelBuilder.Entity("DAL.Entities.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("period_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("PeriodBegining")
                        .HasColumnType("datetime2")
                        .HasColumnName("period_begining");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("period_end");

                    b.HasKey("PeriodId");

                    b.ToTable("period");
                });

            modelBuilder.Entity("DAL.Entities.Student", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("Course")
                        .HasColumnType("int")
                        .HasColumnName("course");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("student_pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("fki_user_id_fkey");

                    b.ToTable("students");
                });

            modelBuilder.Entity("DAL.Entities.StudentsChoice", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SubjectId")
                        .HasName("choises_pkey");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("fki_choises_subject_subject_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("fki_choises_student_user_id");

                    b.ToTable("choices");
                });

            modelBuilder.Entity("DAL.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int")
                        .HasColumnName("lecturer_id");

                    b.Property<int>("MaxNumberOfStudents")
                        .HasColumnType("int")
                        .HasColumnName("max_number_of_students");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfStudents")
                        .HasColumnType("int")
                        .HasColumnName("number_of_students");

                    b.Property<int?>("Semester")
                        .HasColumnType("int")
                        .HasColumnName("semester");

                    b.HasKey("SubjectId")
                        .HasName("subjects_pkey");

                    b.HasIndex("LecturerId")
                        .HasDatabaseName("fki_subject_lecturer_user_id");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("login");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("users_login_key");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DAL.Entities.Lecturer", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithOne("Lecturer")
                        .HasForeignKey("DAL.Entities.Lecturer", "UserId")
                        .HasConstraintName("lecturer_user_user_id_fkey")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Student", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("DAL.Entities.Student", "UserId")
                        .HasConstraintName("student_user_user_id_fkey")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.StudentsChoice", b =>
                {
                    b.HasOne("DAL.Entities.Subject", "Subject")
                        .WithMany("StudentsChoices")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("choises_subject_subject_id")
                        .IsRequired();

                    b.HasOne("DAL.Entities.Student", "User")
                        .WithMany("StudentsChoices")
                        .HasForeignKey("UserId")
                        .HasConstraintName("choises_student_user_id")
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Subject", b =>
                {
                    b.HasOne("DAL.Entities.Lecturer", "Lecturer")
                        .WithMany("Subjects")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("DAL.Entities.Lecturer", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("DAL.Entities.Student", b =>
                {
                    b.Navigation("StudentsChoices");
                });

            modelBuilder.Entity("DAL.Entities.Subject", b =>
                {
                    b.Navigation("StudentsChoices");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("Lecturer");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
